apiVersion: v1
kind: ConfigMap
metadata:
  name: internship-config
  namespace: internship

data:
  APP_ENV: local-kubernetes
  LOG_LEVEL: INFO
  SERVICE_NAME: internship-api

  BACKEND_CORS_ORIGINS: >-
    http://localhost:5173,
    http://127.0.0.1:5173

  CHAT_CORS_ORIGIN: http://localhost:5173
  CHAT_LOG_LEVEL: info
  CHAT_MAX_MESSAGE_LENGTH: "4000"

  JWT_ALGORITHM: HS256

  REDIS_URL: redis://redis:6379

  AWS_REGION: ap-southeast-1
  DYNAMODB_ENDPOINT: http://dynamodb-local:8000
  DYNAMODB_MESSAGES_TABLE: chat_messages
  DYNAMODB_CONVERSATIONS_TABLE: chat_conversations