apiVersion: v1
kind: Secret
metadata:
  name: internship-secrets
  namespace: internship

type: Opaque

stringData:
  SECRET_KEY: replace-with-local-secret

  POSTGRES_DB: internship_tracker
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres

  DATABASE_URL: >-
    postgresql+psycopg2://postgres:postgres@postgres:5432/internship_tracker

  AWS_ACCESS_KEY_ID: local
  AWS_SECRET_ACCESS_KEY: local