from app.core.security import get_password_hash
from app.db.database import Base, SessionLocal, engine
from app.db.models import InternshipApplication, User


def run() -> None:
    Base.metadata.create_all(bind=engine)
    db = SessionLocal()
    try:
        email = "demo@student.edu"
        user = db.query(User).filter(User.email == email).first()
        if not user:
            user = User(
                email=email,
                full_name="Demo Student",
                hashed_password=get_password_hash("password123"),
            )
            db.add(user)
            db.commit()
            db.refresh(user)

        has_app = db.query(InternshipApplication).filter(
            InternshipApplication.user_id == user.id
        ).first()
        if not has_app:
            db.add(
                InternshipApplication(
                    user_id=user.id,
                    company_name="AWS Cloud Internship",
                    position_title="Cloud Engineering Intern",
                    application_status="Saved",
                    job_description=(
                        "We are looking for a student with Python, FastAPI, SQL, "
                        "PostgreSQL, AWS, S3, RDS, Lambda, Docker, Git, and REST API experience."
                    ),
                    notes="Demo application generated by the seed script.",
                )
            )
            db.commit()
        print("Seed data ready: demo@student.edu / password123")
    finally:
        db.close()


if __name__ == "__main__":
    run()
