apiVersion: v1
kind: ConfigMap
metadata:
  name: internship-grafana-datasources
  namespace: monitoring
  labels:
    grafana_datasource: "1"
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Loki
        uid: loki
        type: loki
        access: proxy
        url: http://loki-gateway.monitoring.svc.cluster.local
      - name: Tempo
        uid: tempo
        type: tempo
        access: proxy
        url: http://tempo.monitoring.svc.cluster.local:3100
        jsonData:
          tracesToLogsV2:
            datasourceUid: loki
            tags:
              - service.name
              - pod
              - namespace
