fullnameOverride: kube-prometheus-stack

grafana:
  adminPassword: admin123
  defaultDashboardsTimezone: utc
  defaultDatasourceEnabled: false

  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      labelValue: "1"
      searchNamespace: ALL
    datasources:
      enabled: true
      label: grafana_datasource
      labelValue: "1"
      searchNamespace: ALL

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    serviceMonitorNamespaceSelector: {}
    ruleNamespaceSelector: {}

alertmanager:
  enabled: true

